spring.datasource.url=jdbc:postgresql://localhost:5432/englishApp
#spring.datasource.url=jdbc:postgresql://localhost:5432/englishAppBackup
spring.application.name=wordApp
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.username=foglas
spring.datasource.password=1234
spring.data.jdbc.dialect=postgresql

englishApp.api.requestPath=/englishApp/api

englishApp.word.set.surface = 6
englishApp.word.set.lower_surface = 3
englishApp.word.set.higher_surface = 8
englishApp.word.set.ratio_know = 0.4

englishApp.word.priority.max = 30


logging.level.org.springframework.security=DEBUG
spring.security.disable=false